#!/usr/bin/env bash

: ${DOCKER_CE_VERSION_APT:=18.06.0~ce~3-0~ubuntu}
: ${PACKER_VERSION:=1.2.5}
: ${TERRAFORM_VERSION:=0.11.7}
: ${TERRAFORM_PROVIDER_TEMPLATE_VERSION:=1.0.0}
: ${TERRAFORM_PROVIDER_NULL_VERSION:=1.0.0}
: ${TERRAFORM_PROVIDER_LOCAL_VERSION:=1.1.0}
: ${TERRAFORM_PROVIDER_LIBVIRT_VERSION:=0.4.2}
: ${KUBECTL_VERSION:=1.11.2}
: ${HELM_VERSION:=2.10.0}

if [ -z "$NO_CACHE" ] || [ "$NO_CACHE" = 0 ]; then
    NO_CACHE=""
else
    NO_CACHE="--no-cache"
fi

set -o errexit -o nounset -o pipefail
set -x

which readlink xargs dirname docker

SELF=`readlink -f $0 | xargs dirname`

docker build $NO_CACHE -t k8s-ops $SELF/terraform/ -f- <<EOF
FROM ubuntu:18.04

RUN apt-get -q update \\
 && apt-get -q install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common \\
 && apt-get -q install -y iproute2 openssl openssh-client git rsync vim \\
 && apt-get -q install -y jq python python-pip \\
 && apt-get -q install -y gcc make pkg-config libffi-dev libssl-dev zlib1g-dev python-dev libvirt-dev \\
 && apt-get -q install -y libvirt-clients qemu-system-x86 genisoimage \\
 && update-alternatives --install /usr/bin/mkisofs mkisofs /usr/bin/genisoimage 1 \\
 && apt-get -q clean

RUN pip --no-cache-dir install pyhcl pygments

ENV GOPATH=/go
ENV PATH=\${GOPATH}/bin:\$PATH

RUN mkdir -p \${GOPATH}/bin/ \\
 && add-apt-repository -y ppa:gophers/archive \\
 && apt-get -q update \\
 && apt-get -q install -y golang-1.10-go \\
 && update-alternatives --install /usr/bin/go golang /usr/lib/go-1.10/bin/go 1 \\
 && apt-get -q clean

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \\
 && add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu \$(lsb_release -cs) stable" \\
 && apt-get -q update \\
 && apt-get -q install -y docker-ce=${DOCKER_CE_VERSION_APT} \\
 && apt-get -q clean

RUN set -x \\
 && hashicorp_release_install() { \\
        curl -fsSL https://releases.hashicorp.com/\$1/\$2/\$1_\$2_linux_amd64.zip \\
          | zcat >\${GOPATH}/bin/\$1 \\
         && chmod +x \${GOPATH}/bin/\$1; \\
    } \\
 && hashicorp_release_install packer ${PACKER_VERSION} \\
 && hashicorp_release_install terraform ${TERRAFORM_VERSION} \\
 && hashicorp_release_install terraform-provider-template ${TERRAFORM_PROVIDER_TEMPLATE_VERSION} \\
 && hashicorp_release_install terraform-provider-null ${TERRAFORM_PROVIDER_NULL_VERSION} \\
 && hashicorp_release_install terraform-provider-local ${TERRAFORM_PROVIDER_LOCAL_VERSION}

RUN PKGDIR=\${GOPATH}/src/github.com/dmacvicar/terraform-provider-libvirt \\
 && mkdir -p \${PKGDIR}/ && cd \${PKGDIR}/ \\
 && git clone --depth=1 -b v${TERRAFORM_PROVIDER_LIBVIRT_VERSION} https://github.com/dmacvicar/terraform-provider-libvirt.git . \\
 && go build -o \${GOPATH}/bin/terraform-provider-libvirt

RUN curl -fsSL https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \\
         -o /usr/local/bin/kubectl \\
 && chmod +x /usr/local/bin/kubectl

RUN curl -fsSL https://storage.googleapis.com/kubernetes-helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz \\
    | tar -xz -f- -C /usr/local/bin/ --strip-components=1 linux-amd64/helm \\
 && chmod +x /usr/local/bin/helm

WORKDIR /terraform

ENTRYPOINT []
CMD /bin/bash
EOF

exec docker run --rm \
    --network="host" \
    --privileged="true" \
    -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock:Z \
    -v /var/run/docker.sock:/var/run/docker.sock:Z \
    -v $SELF/terraform/:/terraform/:Z \
    -v $SELF/packer/:/packer/:Z \
    "$@" -it k8s-ops

# vim:ts=4:sw=4:et:syn=sh:
